// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © Ildar Akhmetgaleev (AkhIL)
// See https://github.com/akhilman/vol-poorofile
// vim: shiftwidth=2 tabstop=2

{# Template settings -#}
{% set n_rows = (n_rows or 20) | int -%}
{% set history_n_bars = (history_n_bars or 15) | int -%}
{% set history_row_width = (history_row_width or 10) | float -%}
{% set block_colors = (block_colors or 'purple,teal') | split(',') -%}
{% set boundary_color = boundary_color or 'blue' -%}
{% set recent_n_bars = (recent_n_bars or 150) | int -%}
{% set recent_block_color = recent_block_color or 'gray' -%}
{% set recent_row_width = (recent_row_width or 15) | float -%}
{% set filter_size = (filter_size or 400) | int -%}
{% set max_bars_back = (max_bars_back or 500) | int -%}

//@version=4
study("Poor man's volume profile", "VPoorof", overlay=true, max_bars_back={{max_bars_back}})

enable_history_profiles = input(true, "Enable history profiles")
enable_recent_profile = input(true, "Enable recent profile")
history_n_bars = input({{history_n_bars}}, "Bars in history profile block", minval=1, maxval={{max_bars_back}})
history_row_width = input({{history_row_width}}, "History row width", minval=0)
recent_n_bars = input({{recent_n_bars}}, "Bars in recent profile block", minval=1, maxval={{max_bars_back}})
recent_row_width = input({{recent_row_width}}, "Recent row width", minval=0)
filter_size = input({{filter_size}}, "Profile maximum high pass filter size in bars")
use_custom_volume_source = input(false, "Use custom volume source")
volume_source_symbol = input("", "Custom volume source symbol", input.symbol)

BOUNARY_COLOR = color.{{boundary_color}}
LAST_BLOCK_COLOR = color.{{recent_block_color}}
{%- for color in block_colors %}
HISTORY{{loop.index}}_BLOCK_COLOR = color.{{color}}
{%- endfor %}

custom_volume = use_custom_volume_source ? security(volume_source_symbol, timeframe.period, volume) : volume

////
// Calculate profiles
///

block_index = floor(bar_index / history_n_bars)
block_bar = bar_index % history_n_bars

rolling_high = highest(block_bar + 1)
rolling_low = lowest(block_bar + 1)

block_high = rolling_high[block_bar+1]
block_low = rolling_low[block_bar+1]

// plot(block_high, color=color.green)
// plot(block_low, color=color.green)

row_height = (block_high - block_low) / {{n_rows}}
row_value = custom_volume[history_n_bars] * (max(block_high - block_low, 1) / max(high[history_n_bars] - low[history_n_bars], 1))

{% for n in range(n_rows) %}
row{{n}}_low = block_low + row_height * {{n}}
row{{n}}_high = block_low + row_height * {{n+1}}
row{{n}}_value = high[history_n_bars] > row{{n}}_low and low[history_n_bars] < row{{n}}_high ? row_value : 0
row{{n}}_price = (row{{n}}_low + row{{n}}_high ) / 2
{% endfor %}

// plot(row0_value, color=color.red, style=plot.style_linebr)

if block_bar != 0
	{% for n in range(n_rows) -%}
	row{{n}}_value := row{{n}}_value + row{{n}}_value[1]
	{% endfor %}

highest_row_value = 0.0
if block_bar == history_n_bars - 1
	{% for n in range(n_rows) -%}
	highest_row_value := max(row{{n}}_value, highest_row_value)
	{% endfor %}
else
	highest_row_value := highest_row_value[1]

highest_row_value_avg = ema(highest_row_value, filter_size)

// plot(row0_value)
// plot(highest_row_value, color=color.yellow)
// plot(highest_row_value_avg, color=color.blue)

{% for n in range(n_rows) -%}
row{{n}}_width = floor(history_row_width * row{{n}}_value / highest_row_value_avg)
{% endfor %}

// plot(row0_value, color=color.red, style=plot.style_linebr, offset=-history_n_bars)

////
// Draw history blocks
///
bounds_high_y = enable_history_profiles ? block_high[block_bar+1] : na
bounds_low_y = enable_history_profiles ? block_low[block_bar+1] : na
plot(bounds_high_y, color=BOUNARY_COLOR, style=plot.style_stepline, offset=-history_n_bars*2, title="History block high")
plot(bounds_low_y, color=BOUNARY_COLOR, style=plot.style_stepline, offset=-history_n_bars*2, title="History block low")

{%- for color in block_colors -%}
{%- set hn = (loop.length - loop.index + 1) % loop.length + 1 %}
{%- set num_colors = loop.length %}

history{{hn}}_block_bar = (block_index + {{loop.index}}) % {{num_colors}} * history_n_bars + block_bar

{% for n in range(n_rows) -%}
history{{hn}}_row{{n}}_price = row{{n}}_price[history{{hn}}_block_bar+1]
history{{hn}}_row{{n}}_width = min({{history_n_bars * num_colors - 2}}, row{{n}}_width[history{{hn}}_block_bar+1])
history{{hn}}_row{{n}}_y = enable_history_profiles and history{{hn}}_block_bar <= history{{hn}}_row{{n}}_width ? history{{hn}}_row{{n}}_price : na

{% endfor -%}

{% for n in range(n_rows) -%}
plot(history{{hn}}_row{{n}}_y, color=HISTORY{{hn}}_BLOCK_COLOR, style=plot.style_linebr, linewidth=2, offset=-history_n_bars*2, title="History {{hn}} row {{n}}")
{% endfor -%}
{% endfor %}

////
// Calculate recent profile
///

level_value(from_i, to_i, row_low, row_high) =>
	val = 0.0
	for i = from_i to to_i
		if low[i] < row_high and high[i] > row_low
			val := val + custom_volume[i] * (max((row_high - row_low) * {{n_rows}}, 1) / max(high[i] - low[i], 1))
	val

float recent_high = na
float recent_low = na
float recent_highest_row_value = na
{% for n in range(n_rows) %}
float recent_lvl{{n}}_price = na
int recent_lvl{{n}}_width = na
{% endfor %}

// Estimate bars to end
var int first_bar_time = na
if bar_index == 0
    first_bar_time := time
estimate_bars_to_end = floor((timenow - time) / ((time - first_bar_time) / bar_index))

if enable_recent_profile and estimate_bars_to_end < recent_n_bars * 2
	recent_high := highest(high, recent_n_bars)
	recent_low := lowest(low, recent_n_bars)

	recent_lvl_height = (recent_high - recent_low) / {{n_rows}}
	{% for n in range(n_rows) -%}
	recent_lvl{{n}}_low = recent_low + recent_lvl_height * {{n}}
	recent_lvl{{n}}_high = recent_low + recent_lvl_height * {{n+1}}
	recent_lvl{{n}}_value = level_value(0, recent_n_bars, recent_lvl{{n}}_low, recent_lvl{{n}}_high)
	recent_highest_row_value := max(nz(recent_highest_row_value), recent_lvl{{n}}_value)

	{% endfor %}

	{%- for n in range(n_rows) -%}
	recent_lvl{{n}}_price := (recent_lvl{{n}}_low + recent_lvl{{n}}_high ) / 2
	recent_lvl{{n}}_width := floor(recent_row_width * recent_lvl{{n}}_value / recent_highest_row_value)

	{% endfor %}

////
// Draw recent block
///

var line recent_high_line = na
var line recent_low_line = na
{% for n in range(n_rows) -%}
var line recent_lvl{{n}}_line = na
{% endfor %}

if barstate.islast and enable_recent_profile
	if na(recent_low_line)
		recent_low_line := line.new(bar_index, high, bar_index, high, color=LAST_BLOCK_COLOR)
	if na(recent_high_line)
		recent_high_line := line.new(bar_index, low, bar_index, low, color=LAST_BLOCK_COLOR)
	{% for n in range(n_rows) -%}
	if na(recent_lvl{{n}}_line)
		recent_lvl{{n}}_line := line.new(bar_index, close, bar_index, close, width=2, color=LAST_BLOCK_COLOR)
	{% endfor %}

	line.set_x1(recent_high_line, bar_index)
	line.set_x2(recent_high_line, max(0, bar_index - recent_n_bars))
	line.set_y1(recent_high_line, recent_high)
	line.set_y2(recent_high_line, recent_high)
	line.set_x1(recent_low_line, bar_index)
	line.set_x2(recent_low_line, max(0, bar_index - recent_n_bars))
	line.set_y1(recent_low_line, recent_low)
	line.set_y2(recent_low_line, recent_low)

	{% for n in range(n_rows) -%}
	line.set_x1(recent_lvl{{n}}_line, bar_index - recent_lvl{{n}}_width)
	line.set_x2(recent_lvl{{n}}_line, bar_index)
	line.set_y1(recent_lvl{{n}}_line, recent_lvl{{n}}_price)
	line.set_y2(recent_lvl{{n}}_line, recent_lvl{{n}}_price)
	{% endfor %}

if barstate.islast and not enable_recent_profile
	if not na(recent_low_line)
		line.delete(recent_low_line)
		recent_low_line := na
	if not na(recent_high_line)
		line.delete(recent_high_line)
		recent_high_line := na
	{% for n in range(n_rows) -%}
	if not na(recent_lvl{{n}}_line)
		line.delete(recent_lvl{{n}}_line)
		recent_lvl{{n}}_line := na
	{% endfor -%}
